### ISSUE TITLE
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by 1334233852** [kaigelee/CSFCN#4]
您好！非常感谢您的的工作，我使用了分布式训练，出现下列问题，但是我检测参数的dtype和device并未发现异常，到了  x = self.conv(x)之后就执行不了了，可否咨询下什么问题
Traceback (most recent call last):
  File "/media/cmf/Elements/VOS_related_FANG/XMem/train.py", line 235, in <module>
    model.do_pass(data, total_iter)
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/trainer.py", line 80, in do_pass
    v16, hidden = self.XMem('encode_value', frames[:,0], f16[:,0], hidden, first_frame_gt[:,0])
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/network.py", line 125, in forward
    return self.encode_value(*args, **kwargs)
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/network.py", line 82, in encode_value
    g16, h16 = self.value_encoder(frame, image_feat_f16, h16, masks, others, is_deep_update)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/modules.py", line 225, in forward
    g = self.fuser(image_feat_f16, g)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/modules.py", line 51, in forward
    csfcn_1 = CSFCN(in_channels_sp=g.size(1), out_channels_sp=512, inchannels_cp=1280, out_channel_cp=512).forward(x,g)# [4,512,24,24]  [12,512,24,24]
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/CSFCN.py", line 221, in forward
    x = self.cfc(x)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/CSFCN.py", line 114, in forward
    x = self.reduce_channel(x)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cmf/Elements/VOS_related_FANG/XMem/model/CSFCN.py", line 27, in forward
    x = self.conv(x)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cmf/anaconda3/envs/xmem-repro/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same

**Comment by kaigelee** [comment]
抱歉，提供代码不支持分布式训练。需要针对性的调整
